/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProjectId = IDL.Nat;
export const CommentId = IDL.Nat;
export const Comment = IDL.Record({
  'id' : CommentId,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'projectId' : ProjectId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'title' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'likedBy' : IDL.Vec(IDL.Principal),
  'innovationSummary' : IDL.Text,
  'viewCount' : IDL.Nat,
  'commentCount' : IDL.Nat,
  'category' : IDL.Text,
  'fileBlobIds' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'totalLikes' : IDL.Nat,
  'projectCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([ProjectId, IDL.Text, IDL.Text], [Comment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [Project],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([ProjectId], [Project], ['query']),
  'getProjectComments' : IDL.Func([ProjectId], [IDL.Vec(Comment)], ['query']),
  'getProjects' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getRecentActivity' : IDL.Func(
      [],
      [
        IDL.Record({
          'projects' : IDL.Vec(Project),
          'comments' : IDL.Vec(Comment),
        }),
      ],
      ['query'],
    ),
  'getTopContributors' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProjects' : IDL.Func([IDL.Principal], [IDL.Vec(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeProject' : IDL.Func([ProjectId], [IDL.Nat], []),
  'recordProjectView' : IDL.Func([ProjectId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProjectId = IDL.Nat;
  const CommentId = IDL.Nat;
  const Comment = IDL.Record({
    'id' : CommentId,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'projectId' : ProjectId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'title' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'likedBy' : IDL.Vec(IDL.Principal),
    'innovationSummary' : IDL.Text,
    'viewCount' : IDL.Nat,
    'commentCount' : IDL.Nat,
    'category' : IDL.Text,
    'fileBlobIds' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'totalLikes' : IDL.Nat,
    'projectCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([ProjectId, IDL.Text, IDL.Text], [Comment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [Project],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([ProjectId], [Project], ['query']),
    'getProjectComments' : IDL.Func([ProjectId], [IDL.Vec(Comment)], ['query']),
    'getProjects' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getRecentActivity' : IDL.Func(
        [],
        [
          IDL.Record({
            'projects' : IDL.Vec(Project),
            'comments' : IDL.Vec(Comment),
          }),
        ],
        ['query'],
      ),
    'getTopContributors' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProjects' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeProject' : IDL.Func([ProjectId], [IDL.Nat], []),
    'recordProjectView' : IDL.Func([ProjectId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };