/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'authorId' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'authorName' : string,
  'projectId' : ProjectId,
}
export type CommentId = bigint;
export interface Project {
  'id' : ProjectId,
  'title' : string,
  'authorId' : Principal,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'authorName' : string,
  'description' : string,
  'likedBy' : Array<Principal>,
  'innovationSummary' : string,
  'viewCount' : bigint,
  'commentCount' : bigint,
  'category' : string,
  'fileBlobIds' : Array<string>,
}
export type ProjectId = bigint;
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'displayName' : string,
  'totalLikes' : bigint,
  'projectCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[ProjectId, string, string], Comment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<
    [string, string, Array<string>, string, string, Array<string>, string],
    Project
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[ProjectId], Project>,
  'getProjectComments' : ActorMethod<[ProjectId], Array<Comment>>,
  'getProjects' : ActorMethod<[[] | [string], [] | [string]], Array<Project>>,
  'getRecentActivity' : ActorMethod<
    [],
    { 'projects' : Array<Project>, 'comments' : Array<Comment> }
  >,
  'getTopContributors' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserProjects' : ActorMethod<[Principal], Array<Project>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeProject' : ActorMethod<[ProjectId], bigint>,
  'recordProjectView' : ActorMethod<[ProjectId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUserProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];